

node-api:
  image: 47.97.102.250:5000/node-api:latest
  container_name: node-api
  restart: always
  ports:
    - 8000:8000
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ../config/app.config.js:/workspace/app.config.js