

node-api:
  image: 127.0.0.1:5000/node-api:latest
  container_name: node-api
  restart: always
  ports:
    - 8080:8080
  volumes:
    - /etc/localtime:/etc/localtime:ro
  links:
    - redis:redisio
    - mongodb:mongodb

redis:
  restart: always
  image: sameersbn/redis:latest
  ports:
    - 6379:6379
  volumes:
    - /opt/gitlab/redis:/var/lib/redis
    - /etc/localtime:/etc/localtime:ro

mongodb:
  restart: always
  ports:
    - 27017:27017
  image: mongo:latest
  volumes:
    - ./mongo/db:/data/db